### ISSUE TITLE
toListUnordered isn't Tail Recursive

### ISSUE THREAD

**Issue by NeilW** [TSFoster/elm-heap#3]
I notice that `toListUnordered `tends to blow the call stack for around 30,000 items as `flattenStructure` isn't tail recursive.

Anyway of doing it with some sort of accumulator?

**Comment by TSFoster** [comment]
Ooh thanks, should have noticed that when I wrote it.

Version 2.1.2 published with tail-recursive `toListUnordered`

**Comment by TSFoster** [comment]
I'll try to find some time to go through this package and check performance, but if you notice anything else, just raise another issue!
